### ISSUE TITLE
Error running opensea.ts: "Property 'sender' is private and only accessible within class 'NearEthAdapter'"

### ISSUE THREAD

**Issue by mikedotexe** [Mintbase/near-ca#18]
Hey folks! I think your example may be more presentable as well as helpful for hackathoners in the upcoming ETH Seoul and BUIDL Asia conferences.

I'm running through it now and ran this command, which I found in the README:

    npx ts-node examples/opensea.ts

<img width="1442" alt="Screenshot 2024-03-24 at 2 02 34 PM" src="https://github.com/Mintbase/near-ca/assets/1042667/e9ed5d7a-2ed3-4d74-a7da-eea444ba7bbf">

I've got the `.env` file set up correctly, I believe (y'all made it easy, ty)

<img width="1415" alt="Screenshot 2024-03-24 at 2 06 48 PM" src="https://github.com/Mintbase/near-ca/assets/1042667/3e9ecba7-a92b-40b9-8666-a9ae9299d19b">

I'm using NodeJs `v18.18.0`

**Comment by bh2smith** [comment]
Closed by https://github.com/Mintbase/near-ca/commit/02440333c7f564f7117d224c2f09b8253ec13f4f
