### ISSUE TITLE
(Minor) Update root pubkey in test

### ISSUE THREAD

**Issue by mikedotexe** [Mintbase/near-ca#51]
Looks like the root key was changed to:

`secp256k1:4NfTiv3UsGahebgTaHyD9vF8KYKMBnfd6kh94mK6xv8fGBiJB8TBtFMP5WWXz6B89Ac1fbpzPwAvoyQebemHFwx3`

Looks like this could get updated if you think it's important:

https://github.com/Mintbase/near-ca/blob/c674abfe70dcd6a95479689536ac4bf4c9ac9173/tests/unit/utils.kdf.test.ts#L8

I found that updated on this page:

https://docs.near.org/build/chain-abstraction/chain-signatures#1-deriving-the-foreign-address

**Comment by bh2smith** [comment]
Hey, thanks for letting me know about the change of root key. I think that for the purpose of our unit tests this key doesn't really matter. If we change the key, then we will also have to change all the expected results. Perhaps it is best to just add a comment inline to the docs containing the actual root key.

**Comment by bh2smith** [comment]
This was updated during test corrections for the MPC contract update:
https://github.com/Mintbase/near-ca/pull/65

In fact this issue actually helped during debugging. 
Thanks @mikedotexe for reporting.
